api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        yaml: ['application/x-yaml']
        html: ['text/html']
        multipart: ['multipart/form-data']
